on:
  pull_request:
    branches:
      - main

jobs:
  wilco:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    name: Pr checks

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_PASSWORD: postgres
          SECRET_KEY: secret
          POSTGRES_DB: anythink-market
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Check out project
        uses: actions/checkout@v2
